Migrate to top-level `/content` directory
davestewart/nuxt-content-assets pull request #86
Opened 2024-08-11 00:31 UTC by JakeIsMeh

`package-lock.json` should be regenerated as `package.json` was modified and playground dependencies might have to be upgraded, which I am leaving to you. (the branch is open for maintainers to edit)

(Side note: I used `pnpm` as I encountered many issues with `npm` while trying to set up the dev environment for this repo.)

closes: #85

2024-09-06 21:08 UTC, mathieunicolas commented
Thanks for this PR ❤️
Poke @davestewart, if this PR solve the problem with nuxt 4 could you merge please it ?
Thanks a lot !

2024-09-06 22:14 UTC, davestewart commented
Sorry, been slammed with work but looking to take some time to catch up on oss so will take a look over the weekend 👍

2024-09-07 09:52 UTC, davestewart requested changes

2024-09-07 09:52 UTC, davestewart commented on src/module.ts
Is this compatible with both Nuxt 3 and Nuxt 4?

It seems we could check for both folders, no?

2024-09-07 11:35 UTC, JakeIsMeh commented on src/module.ts
It should be compatible AFAIK.

The breaking change with Nuxt 4 was that the *default* `<srcDir>` was changed to `<rootDir>/app`, whereas with Nuxt 3 `srcDir` essentially pointed to `<rootDir>`.

With Nuxt Content 2.13+, your *default* `/content` folder is now relative to `<rootDir>` rather than `<srcDir>` (see https://github.com/nuxt/content/pull/2649).

Therefore, this shouldn't be a breaking change for us either because:
- For Nuxt 3, `default <srcDir> === default <rootDir>`
- the onus of breakage (and migration) is on `@nuxt/content@^2.13.0`
- people who've specified custom sources shouldn't be affected since this code path only runs to find the *default* `content/` folder

2024-09-07 13:13 UTC, davestewart commented on src/module.ts
Yeah, that makes sense. Thanks for explaining; it's been ages since I looked at the code!

2024-09-27 15:53 UTC, mathieunicolas commented
Hi, is everything ready for a merge ?
@davestewart shall we look for deeper changes to help you with this one ?

Thanks !

2024-10-06 04:57 UTC, davestewart approved these changes
All good, and thanks for waiting for me to get to this!

2024-10-06 04:58 UTC, merged

2024-10-06 07:11 UTC, davestewart commented
Hey @JakeIsMeh ...  
  
So I merged your code but have since found out that the playground doesn't work at all.  
  
I've renamed `app/app.vue` to `app/index.vue` which allows the site to run, but none of the images are getting served.

It's been so long since I looked at the code I'm not 100% sure myself what isn't working.  
  
I'm not going to publish anything to NPM until I can be sure what's going on.  
  
I'm away on holiday right now, but would like to get this over the line seeing as we've started!

2024-10-06 10:44 UTC, JakeIsMeh commented
Hey @davestewart,

I had a gander at this and want to say that none of the code here has rotted, but rather, this was a series of unfortunate events.

I'm not sure which issues you ran into specifically but I did encounter some issues when setting up the playground to test again.

- Missing dependencies (npm being bad as usual)
  - Used pnpm instead (do not migrate the lockfile (i.e. run `pnpm i` while `package-lock.json` still exists), instead delete `package-lock.json` and let pnpm use it's more robust resolution algorithm to generate a fresh lockfile)

- Nuxt entry could not resolve the `ipx` package
  - For some reason, the generated nuxt entry file is looking for `ipx` in the flat directory rather than using the full pnpm path import (file://path/to/proj/node_modules/.pnpm/ipx@3.0.1/index.js)
  - You could use `--shamefully-hoist` when installing the playground, I opted to just add `ipx` to the playground's devDeps
  
- `NuxtImage.ts` proxy component fails to import `nuxt-img.mjs`
  - From @nuxt/image@1.7.1 onwards, the runtime components aren't compiled into js anymore, but rather distributed as the raw Vue component
  - Updated the import
  - We should probably update the minimum version specified in package.json too

Afterwards, the playground works just fine.

I've uploaded the repo here for reference:
https://github.com/JakeIsMeh/nuxt-content-assets/tree/debugging

Cheers

2024-10-07 09:41 UTC, JakeIsMeh commented
Quick update: with further testing, the only issues I could find are:
-  During SSG (`nuxi generate`), linked JSON data (`JSON.json` in the playground) will cause the build to fail due to the crawler trying to pre-render it but it 404s (intended behaviour, see #79)
- Sometimes building will fail due to missing files (that nuxt-content-assets were supposed to copy). Running `nuxi cleanup` allows projects to build but after a while it happens again. Currently unsure of how to reproduce it.

2024-10-07 18:55 UTC, davestewart commented
Do you think this is a Nuxt 4 issue?

2024-10-08 23:09 UTC, JakeIsMeh commented
Hi @davestewart, quick update, I've opened an issue for the build failure (#88).

As for the linked json data issue, I'm not sure if it ever worked with SSG as I didn't utilize it, but it seems like either a pre-existing bug, or if it did used to work during SSG, one caused by changes to the internals of `@nuxt/content`.